Fix Bundle #2: Fixed Sidenav Inner Children rendering issues, Link content not inlined, Breadcrumbs fix for missing index directories
makerdao/community-portal pull request #86
Opened 2020-07-02 13:55 UTC by MaximumCrash

### Attention (CC)
@twblack88 
@andytudhope 
@isaacpearl 

## Summary of changes
- Fixed Sidenav children that didn't have index pages from not being rendered, causing the sidenav to have missing children. (ie. The case where /work_with_us/governance/take-notes <-- THIS Doesn't have an index file, but it has children)
- Added chevrons to sidenav nodes that have children, this wasn't in the spec, but it's obvious that it's needed. 
- Fixed Link inner content not being inlined (sometimes copy would be rendered as a div and divs are block elements by default)
- Fixed breadcrumbs having similar missing index issue as the sidenav. 

## Motivation & Context
- Issue #82, #83 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation Update
- [ ] Other (please describe):

## Does this introduce a breaking change?

_Breaking change is defined as_ **"A fix or feature that would cause existing functionality to change."**

- [ ] Yes
- [x] No

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added/changed necessary documentation (if appropriate)
- [ ] All new and existing tests passed.

## How Has This Been Tested?
Locally

## Screenshots (if appropriate):

2020-07-02 17:48 UTC, MaximumCrash commented
@all-contributers please add @MaximumCrash for code

2020-07-03 00:44 UTC, twblack88 commented on README.md
> +    _This project makes use of `yarn`. You'll likely need to use npm to get everything setup once cloned._
_This project makes use of `yarn`. Don't forget to run `yarn` once before starting the environment up.

2020-07-03 00:52 UTC, twblack88 requested changes
everything is super clear and looks up to snuff. I wrote out one change to the readme that, hopefully, adds some clarity. We'll keep tinkering on that tho.

2020-07-05 17:21 UTC, isaacpearl approved these changes

2020-07-06 10:44 UTC, MaximumCrash commented
Other PRs that started from this PR's branch have been merged in prior. No need to deal with conflicts.

2020-07-06 10:44 UTC, closed without merging